run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - misspell
  disable-all: false

linters-settings:
  govet:
    enable-all: false

issues:
  exclude-rules:
    - linters: [errcheck]
      text: "Error return value of .*(Close|Flush|Write|Log).*is not checked"
